# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-04 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_auto_20190103_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='average',
        ),
    ]
